name: build 

on:
  push:
    branches:
      - app-service
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft' # See 'Supported distributions' for available options
        java-version: '11'

    - name: Build application and run tests
      run: mvn clean install

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: target/ROOT.war
        if-no-files-found: error

  publish:
    name: Deploy WAR and supporting files
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: actions/checkout@v2
        
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: app
    
    - name: Deploy to App Service
      run: | 
        az webapp deploy \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name ${{secrets.WEBAPP}} \
          --src-path ./ROOT.war \
          --type war \
          --restart false